volumes: []
services:
  - name: runtime
    image: rust
    env:
      - name: FIRST_TIME_CACHE
        value: /ide/.ft_cache
      - name: INIT_FILE_OPEN
        value: /app/main.rs
    volumeMounts: []
    limits:
      cpu: 2
      memory: 8
  - name: db
    image: mysql:8
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: aBadPassword123
      - name: MYSQL_DATABASE
        value: paymentsdb
    volumeMounts: []
    limits:
      cpu: 1
      memory: 4
  - name: cache
    image: redis
    env: []
    volumeMounts: []
    limits:
      cpu: 1
      memory: 2
tasks:
  - name: init-db
    command: sh /workspace/init-db.sh
    serviceName: db
    type: exec
