volumes: []
services:
  - name: runtime
    image: rust
    env: []
    volumeMounts: []
    limits:
      cpu: 2
      memory: 8
  - name: db
    image: mysql:8
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: aBadPassword123
    volumeMounts: []
    limits:
      cpu: 1
      memory: 4
  - name: cache
    image: redis
    env: []
    volumeMounts: []
    limits:
      cpu: 1
      memory: 2
tasks:
  - name: init-db
    command: sh /workspace/init-db.sh
    serviceName: db
    type: exec