version: '3'
services:
  rust:
    build: ./Dockerfile
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: paymentsdb
      MYSQL_RANDOM_ROOT_PASSWORD: aBadPassword123
    ports:
      - 3306:3306